steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "gcr.io/go-world-409920/go-hello-00001-n7r", ".", "-f", "Dockerfile" ]

  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/go-world-409920/go-hello-00001-n7r" ]